openapi: 3.0.0
info:
  title: 'Cloudbeds API v2'
  description: '<p>Welcome to the documentation for <strong>Cloudbeds API Version v2</strong>! If you are looking to learn how to use the Cloudbeds API to access guest information, reservations, or similar data for your Cloudbeds customers, then you''ve come to the right place.</p><p>In this document you will find all the API methods we provide along with explanations for parameters and response examples.</p><p>If you have questions about different implementation steps (e.g. how to implement OAu[...]'
  version: v2
servers:
  -
    url: 'https://api.cloudbeds.com/'
    description: 'Cloudbeds API v2'
paths:
  /integration/v1/connected-applications:
    get:
      tags:
        - Applications
      summary: 'Get all connected API clients for a property'
      operationId: 'ApiClientController::connectedApiClients'
      security:
        -
          default: []
  '/doorlock/v1/keys/{propertyId}':
    get:
      tags:
        - 'Door Lock Keys'
      summary: 'Get a list of doorlock keys for a specific app client and property.'
      operationId: 'DoorLockKeyController::index'
      security:
        -
          default:
            - 'read:doorLockKey'
  /doorlock/v1/keys:
    post:
      tags:
        - 'Door Lock Keys'
      summary: 'Create a new doorlock key.'
      operationId: 'DoorLockKeyController::create'
      security:
        -
          default:
            - 'write:doorLockKey'
    delete:
      tags:
        - 'Door Lock Keys'
      summary: 'Delete a list of doorlock keys.'
      operationId: 'DoorLockKeyController::batchDelete'
      security:
        -
          default:
            - 'delete:doorLockKey'
  '/doorlock/v1/keys/{id}':
    delete:
      tags:
        - 'Door Lock Keys'
      summary: 'Delete a doorlock key.'
      operationId: 'DoorLockKeyController::delete'
      security:
        -
          default:
            - 'delete:doorLockKey'
    patch:
      tags:
        - 'Door Lock Keys'
      summary: 'Update a doorlock key.'
      operationId: 'DoorLockKeyController::update'
      security:
        -
          default:
            - 'write:doorLockKey'
  '/doorlock/v1/settings/{propertyId}':
    get:
      tags:
        - 'Door Lock Settings'
      summary: 'Get doorlock settings for property for specific application client.'
      operationId: 'DoorLockSettingsController::single'
      security:
        -
          default:
            - 'read:doorLockKey'
    put:
      tags:
        - 'Door Lock Settings'
      summary: 'Upsert doorlock settings for property for specific application client.'
      operationId: 'DoorLockSettingsController::upsert'
      security:
        -
          default:
            - 'write:doorLockKey'
    delete:
      tags:
        - 'Door Lock Settings'
      summary: 'Delete doorlock settings for property for specific application client.'
      operationId: 'DoorLockSettingsController::delete'
      security:
        -
          default:
            - 'delete:doorLockKey'
  '/housekeeping/v1/inspections/{propertyId}':
    get:
      tags:
        - Housekeeping
      summary: 'Housekeeping inspection list'
      operationId: 27abd48cb30106ec3251cf3baf34174c
      security:
        -
          default:
            - 'read:housekeeping'
  /integration/v1/events:
    get:
      tags:
        - 'Integration Events'
      summary: 'Get a list of integration events for a specific property.'
      operationId: 'IntegrationEventController::index'
      security:
        -
          default: []
    post:
      tags:
        - 'Integration Events'
      summary: 'Create a new integration event.'
      operationId: 'IntegrationEventController::create'
      security:
        -
          default:
            - 'write:appError'
  '/integration/v1/events/{id}':
    patch:
      tags:
        - 'Integration Events'
      summary: 'Update an integration event.'
      operationId: 'IntegrationEventController::update'
      security:
        -
          default:
            - 'write:appError'
  '/integration/v1/events/{id}/retry':
    post:
      tags:
        - 'Integration Events'
      summary: 'Retry an integration event.'
      operationId: 'IntegrationEventController::retry'
      security:
        -
          default: []
  /item/v1/custom-items:
    get:
      tags:
        - Items
      summary: 'Get a list of custom items for a specific property.'
      operationId: 'CustomItemController::index'
      security:
        -
          default:
            - 'read:item'
  /market-segmentation/v1/groups:
    get:
      tags:
        - market-segmentation-groups
      summary: 'Get a list of Market Segmentation Groups.'
      operationId: 'GroupController::index'
      security:
        -
          default:
            - 'read:marketsegment'
    post:
      tags:
        - market-segmentation-groups
      summary: 'Create a new Market Segmentation Group.'
      operationId: 'GroupController::create'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/groups/{id}':
    get:
      tags:
        - market-segmentation-groups
      summary: 'Get Market Segmentation Group data.'
      operationId: 'GroupController::single'
      security:
        -
          default:
            - 'read:marketsegment'
    delete:
      tags:
        - market-segmentation-groups
      summary: 'Delete a Market Segmentation Group.'
      operationId: 'GroupController::delete'
      security:
        -
          default:
            - 'delete:marketsegment'
    patch:
      tags:
        - market-segmentation-groups
      summary: 'Update a Market Segmentation Group.'
      operationId: 'GroupController::update'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/groups/{id}/enable':
    post:
      tags:
        - market-segmentation-groups
      summary: 'Enable a Market Segmentation Group.'
      operationId: 'GroupController::enable'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/groups/{id}/disable':
    post:
      tags:
        - market-segmentation-groups
      summary: 'Disable a Market Segmentation Group.'
      operationId: 'GroupController::disable'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/segments/{enabled}':
    get:
      tags:
        - market-segmentation-segments
      summary: 'Get a list of Market Segmentation Segments.'
      operationId: 'SegmentController::index'
      security:
        -
          default:
            - 'read:marketsegment'
  '/market-segmentation/v1/segments/{id}':
    get:
      tags:
        - market-segmentation-segments
      summary: 'Get Market Segmentation Segment data.'
      operationId: 'SegmentController::single'
      security:
        -
          default:
            - 'read:marketsegment'
    delete:
      tags:
        - market-segmentation-segments
      summary: 'Delete a Market Segmentation Segment.'
      operationId: 'SegmentController::delete'
      security:
        -
          default:
            - 'delete:marketsegment'
    patch:
      tags:
        - market-segmentation-segments
      summary: 'Update a Market Segmentation Segment.'
      operationId: 'SegmentController::update'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/segments/{id}/reservations/{active}':
    get:
      tags:
        - market-segmentation-segments
      summary: 'Get a list of reservations linked to a Market Segmentation Segment.'
      operationId: 'SegmentController::reservations'
      security:
        -
          default:
            - 'read:marketsegment'
  /market-segmentation/v1/segments:
    post:
      tags:
        - market-segmentation-segments
      summary: 'Create a new Market Segmentation Segment.'
      operationId: 'SegmentController::create'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/segments/{id}/enable':
    post:
      tags:
        - market-segmentation-segments
      summary: 'Enable a Market Segmentation Segment.'
      operationId: 'SegmentController::enable'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/segments/{id}/disable':
    post:
      tags:
        - market-segmentation-segments
      summary: 'Disable a Market Segmentation Segment.'
      operationId: 'SegmentController::disable'
      security:
        -
          default:
            - 'write:marketsegment'
  '/market-segmentation/v1/segments/{id}/default':
    post:
      tags:
        - market-segmentation-segments
      summary: 'Set Market Segmentation Segment as Default.'
      operationId: 'SegmentController::default'
      security:
        -
          default:
            - 'write:marketsegment'
  /rates/v1/rate-plans:
    get:
      tags:
        - 'Rate Plans'
      summary: 'Get a list of Rates Plans.'
      operationId: 'RatePlanController::index'
      security:
        -
          default:
            - 'read:rates'
    post:
      tags:
        - 'Rate Plans'
      summary: 'Create a new Rate Plan.'
      operationId: 'RatePlanController::create'
      security:
        -
          default:
            - 'write:rates'
  '/rates/v1/rate-plans/{id}':
    get:
      tags:
        - 'Rate Plans'
      summary: 'Get Rate Plan data.'
      operationId: 'RatePlanController::single'
      security:
        -
          default:
            - 'read:rates'
    delete:
      tags:
        - 'Rate Plans'
      summary: 'Delete a Rate Plan.'
      operationId: 'RatePlanController::delete'
      security:
        -
          default:
            - 'delete:rates'
    patch:
      tags:
        - 'Rate Plans'
      summary: 'Update an existing Rate Plan.'
      operationId: 'RatePlanController::update'
      security:
        -
          default:
            - 'write:rates'
  /rooms/v1/out-of-service:
    post:
      tags:
        - rooms
      summary: 'Room out of service'
      operationId: 'OutOfServiceController::make'
      security:
        -
          default:
            - 'write:room'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
    default:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.cloudbeds.com/auth/oauth/authorize'
          tokenUrl: 'https://api.cloudbeds.com/auth/oauth/token'
          scopes:
            'read:doorLockKey': 'Read DoorLock keys and settings'
            'write:doorLockKey': 'Write DoorLock keys and settings'
            'delete:doorLockKey': 'Delete DoorLock keys and settings'
            'read:housekeeping': 'Read Housekeeping inspections'
            'read:marketsegment': 'Read Market Segmentation groups and segments'
            'write:marketsegment': 'Write Market Segmentation groups and segments'
            'delete:marketsegment': 'Delete Market Segmentation groups and segments'
            'write:importTask': 'Create new data imports'
            'read:importTask': 'Read data imports'
            'hotel:read': 'Read Hotel information'
            'hotel:write': 'Write Hotel information'
            'hotel:delete': 'Delete Hotel information'
            'write:appError': 'Write AppError information'
tags:
  -
    name: Applications
    description: Applications
  -
    name: 'Door Lock Keys'
    description: 'Door Lock Keys'
  -
    name: 'Door Lock Settings'
    description: 'Door Lock Settings'
  -
    name: Housekeeping
    description: Housekeeping
  -
    name: 'Integration Events'
    description: 'Integration Events'
  -
    name: Items
    description: Items
  -
    name: market-segmentation-groups
    description: market-segmentation-groups
  -
    name: market-segmentation-segments
    description: market-segmentation-segments
  -
    name: 'Rate Plans'
    description: 'Rate Plans'
  -
    name: rooms
    description: rooms
